# 定义 API 版本和资源类型
apiVersion: apps/v1
kind: Deployment
# 部署元数据配置
metadata:
  # 部署名称
  name: xpanse-ui-deployment
  # 应用标签，用于选择器匹配
  labels:
    app: xpanse-ui

# 部署规范详细设置
spec:
  # 副本数，即运行的容器实例数量
  replicas: 3

  # 选择器，确保 Pod 与 Deployment 关联
  selector:
    matchLabels:
      app: xpanse-ui

  # Pod 模板，定义新创建的 Pod 的外观
  template:
    metadata:
      # Pod 标签
      labels:
        app: xpanse-ui

    # Pod 内容规范
    spec:
      # 容器列表，此处只有一个容器
      containers:
        - name: xpanse-ui
          image: ghcr.io/eclipse-xpanse/xpanse-ui:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: xpanse-ui-service
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30008
