
apiVersion: v1
kind: ConfigMap
metadata:
  name: xpanse-configmap
data:
  application.properties: |
    spring.profiles.active=oauth,zitadel,zitadel-testbed,mysql
    spring.datasource.url=policy.man.endpoint=http://localhost:8090
  application-mysql.properties: |
    spring.datasource.username=xpanse
    spring.datasource.password=Xpanse@2024
    spring.datasource.name=mysql
    spring.datasource.url=jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true
    spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
  application-zitadel.properties: |
    authorization.server.endpoint=https://iam.xpanse.site
    authorization.api.client.id=221665786966638595@eclipse-xpanse
    authorization.api.client.secret=2S7yZR4jWauyE3wLHM1h5asc0WNWdBUXAw2Ill3Pmu0qM4D3LWBCwikXbsG81ycl
    authorization.swagger.ui.client.id=221664356859969539@eclipse-xpanse
    authorization.token.type=JWT
    oauth.protected.api.client.id=apiclient
    oauth.protected.api.client.secret=xkXXgZFf85OAvzHzj6KGQKIPHoieb0TeEElAojokOHv44lCUVwAKL8rFLVgcg3L4

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xpanse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xpanse
  template:
    metadata:
      labels:
        app: xpanse
    spec:
      containers:
        - name: xpanse-container
          image: ghcr.io/eclipse-xpanse/xpanse:v1.0.17
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: xpanse-configmap
            items:
              - key: application.properties
                path: application.properties

---
apiVersion: v1
kind: Service
metadata:
  name: xpanse-service
spec:
  type: ClusterIP
  selector:
    app: xpanse
  ports:
    - name: http
      port: 8080
      targetPort: 8080